### PR TITLE
Updates and markup cleanup

### PR DESCRIPTION
**Pull request by hohMiyazawa**
Misc. minor stuff, can be divided into separate pull requests if required.

- Update readme to point to the now live https://jpegxl.info/
- Include second ImageReady video.
- Paragraph element semantics (mainly, not allowed to contain ul elements)
- Lossless (ECT) optimisation of the heavy comparison PNG. It's the single largest part of the site, and the gain is substantial, >100kB. (and we're making a point about compression, yes?)

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
I do not have a google account, which seems to be required to sign the CLA. Well then.

Is this really necessary? Are there alternative ways of signing?

**Comment by jonsneyers** [comment]
We can ignore the CLA bot for website updates, right @deymo ?

**Comment by deymo** [comment]
I don't know about that, my guess is that no, we can't ignore the CLA for external contributions.

AFAIK there's no other way to sign the CLA than to log in with a Google account, which hasn't been a problem for many people.

Maybe this is not the best place to host that website.

**Comment by hohMiyazawa** [comment]
As far as I can see, the legal text is about making the terms of licensing unambiguous for individuals keeping their copyright.

I do not wish to cause any trouble, so as a one-off I could (if requested) sign over copyright to Jon Sneyers, who I trust will manage it wisely :)

**Comment by hohMiyazawa** [comment]
I'm assuming the move of the repo to https://github.com/jxl-community/jxl-community.github.io resolves this.

**Pull request merged**
